### ISSUE TITLE
[Cleanup] Buildings menu should not be hardcoded

### ISSUE THREAD

**Issue by CatalystOfNostalgia** [CatalystOfNostalgia/gravehub#12]
Let's unhardcode the buildings menu. The buildings available should be determined based on what the server says the user can build.

**Comment by CatalystOfNostalgia** [comment]
For this sprint, just get what buildings can be built from server.

**Comment by AnthonyDario** [comment]
@raoanjana what information will you need for this? I will need to update the server so it can give you the information you need.
