### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by CatalystOfNostalgia** [CatalystOfNostalgia/gravehub#19]
Let's 1) add a few second animation when a building is built and 2) add sound effects.

**Comment by aj770077** [comment]
I got the sound on this - Austin E.

**Comment by CatalystOfNostalgia** [comment]
Cool. You should upload it to the game dev drive and comment with where it is.

**Comment by jrg94** [comment]
Sounds are in I think

**Comment by tkk21** [comment]
poof and elemari makes noise
