### ISSUE TITLE
Save User Config to server as well

### ISSUE THREAD

**Issue by tkk21** [CatalystOfNostalgia/gravehub#37]
Now that Setting menu is implemented, the game should be able to save the user's volume and music playlist.

This can either be saved locally or to the server. This is up to debate.

**Comment by CatalystOfNostalgia** [comment]
This should go into the user's json for when the game saves. Let's block this until after #15. I'll set this to be due on Nov 10.

**Comment by CatalystOfNostalgia** [comment]
@Dacoolchicken As we discussed, let's also include fixing the game load as well.

**Comment by CatalystOfNostalgia** [comment]
It actually does work!
