### ISSUE TITLE
Resize Box Colliders on Buildings

### ISSUE THREAD

**Issue by jrg94** [CatalystOfNostalgia/gravehub#79]
Each of the buildings has a box collider which is large. This means that buildings closer to the camera will take precedence during ray casting. You'll notice this issue if you place a building 'below' another building and try to click on the top building to pull up its option menu. You'll most likely open the bottom buildings option menu due to the large size of the collider.

**Comment by CatalystOfNostalgia** [comment]
Requirements for this:
1. Building menu should display only the level 1 buildings (all other buildings are generated from updating)
2. We should display the resource cost for creating the building 
3. Only display buildings the user has the HQ level to build
4. Only display those buildings which the user has not already built. 
5. Fix the box on the building.
