### ISSUE TITLE
Dynamically create poofs based off of buildings and resources

### ISSUE THREAD

**Issue by raoanjana** [CatalystOfNostalgia/gravehub#80]

**Comment by CatalystOfNostalgia** [comment]
Requirements for this. 
1. The residences set the maximum available number of poofs and that number shouldn't be exceeded.
2. The poof counter should display the number of poofs/the maximum possible amount of poofs.

**Comment by whh34** [comment]
Apparently I need to inform you that the saving of resources from SaveState needs to be tested; you know, once saving is a thing again.

**Comment by tkk21** [comment]
This is done
